[package]
name = "node2vec-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.19", features = ["dataset", "train", "ndarray", "wgpu"] }
csv = "1.4.0"
rand = "0.9.2"
rayon = "1.11.0"
rustc-hash = "2.1.1"
